[[ -f "$HOME/.zsh/functions.zsh" ]] && source "$HOME/.zsh/functions.zsh"

export ZSH="$HOME/.oh-my-zsh"
export LANG=en_US.UTF-8
export SPACESHIP_CONFIG="$HOME/.config/spaceship/spaceship.zsh"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
# export PATH="/usr/local/anaconda3/bin:$PATH"
export PATH="$HOME/.flutter/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin"

export SDKMAN_DIR="$HOME/.sdkman"

if [[ $(uname -m) == 'arm64' ]]; then
    export PATH="/opt/homebrew/bin:$PATH"
    export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
fi

if chrome_path=$(locate_chrome); then
  export CHROME_EXECUTABLE="$chrome_path"
fi

if [[ -d "$HOME/.rbenv" && ! "$PATH" =~ "$HOME/.rbenv/bin" ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
fi

# Custom ENV Variable
export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1