# tap "dart-lang/dart"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "nextdns/tap"
# tap "sass/sass"
tap "teamookla/speedtest"

# set arguments for all 'brew cask install' commands
cask_args appdir: "~/Applications"

# Installing AppStore Utility and Xcode First
brew "mas"
mas "Xcode", id: 497799835

brew "openssl@1.1"
brew "openssl@3"
brew "autoconf"
brew "automake"
brew "bat"
brew "bitwarden-cli"
brew "bpytop"
brew "python@3.8"
brew "python@3.9"
brew "python@3.10"
brew "glib"
brew "carthage"
brew "coreutils"
brew "ruby"
brew "fastlane"
brew "pkg-config"
brew "harfbuzz"
brew "ffmpeg"
brew "gh"
brew "gcc"
brew "git"
brew "git-flow"
brew "git-lfs"
brew "graphicsmagick"
brew "htop"
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "libheif"
brew "imagemagick"
brew "ios-deploy"
# brew "jmeter"
# brew "jupyterlab"
brew "libksba"
brew "mkcert"
# brew "macvim"
# brew "mysql"
brew "nginx", restart_service: true
brew "neovim"
brew "openconnect"
brew "opencv@3"
brew "openvpn"
brew "openconnect"
brew "pyenv"
brew "rbenv"
brew "ruby-build"
brew "rclone"
brew "rsync"
brew "subversion"
brew "swiftlint"
brew "teleconsole"
brew "telnet"
brew "tmux"
brew "whalebrew"
brew "youtube-dl"
brew "zlib"
brew "zsh"
brew "zsh-completions"
brew "nextdns/tap/nextdns"
# brew "sass/sass/sass"
brew "teamookla/speedtest/speedtest"

# Installing casks

cask "alfred"
# cask "anaconda"
cask "android-file-transfer"
cask "android-platform-tools"
cask "clickup"
cask "docker"
cask "easyfind"
# cask "firefox"
cask "font-fira-code"
cask "font-source-code-pro"
cask "font-cascadia-code"
cask "forticlient-vpn"
cask "gotomeeting"
cask "google-chrome"
cask "hyper"
cask "hp-easy-start"
cask "iterm2"
cask "itsycal"
cask "jetbrains-toolbox"
cask "kite"
cask "little-snitch"
cask "micro-snitch"
cask "microsoft-office"
cask "microsoft-teams"
cask "macfuse"
cask "osxfuse"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "mongodb-realm-studio"
cask "notion"
cask "setapp"
cask "simpholders"
cask "simsim"
cask "skype"
cask "snagit"
cask "sourcetree"
cask "suspicious-package"
cask "termius"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "webpquicklook"
# cask "zoom"

# App store installation
mas "Amphetamine", id: 937984704
mas "Encrypto", id: 935235287
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Mactracker", id: 430255202
# mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paste JSON as Code • quicktype", id: 1330801220
mas "Realm Browser", id: 1007457278
mas "Swiftify for Xcode", id: 1183412116
# mas "Speedify", id: 999025824
mas "Text Toolset", id: 1157225201