---
- name: Homebrew CLI Installation
  community.general.homebrew:
    upgrade_all: true
    state: latest
    name:
      - openssl@1.1
      - openssl@3
      - act
      - atuin
      - autoconf
      - automake
      - bat
      - bitwarden-cli
      - btop
      - glib
      - carthage
      - chezmoi
      - coreutils
      - dust
      - eza
      - fastlane
      - harfbuzz
      - ffmpeg
      - gh
      - gcc
      - git
      - git-flow
      - git-lfs
      - git-delta
      - gnupg
      - graphicsmagick
      - htop
      - libimobiledevice
      - ideviceinstaller
      - libheif
      - imagemagick
      - ios-deploy
      - libksba
      - mkcert
      - nginx
      - neovim
      - neofetch
      - opencv@3
      - openvpn
      - openconnect
      - pkg-config
      - pyenv
      - python@3.10
      - python@3.11
      - python@3.12
      - poetry
      - rbenv
      - ruby-build
      - ruby
      - rclone
      - rsync
      - subversion
      - swiftlint
      - telnet
      - thefuck
      - tlrc
      - tmux
      - whalebrew
      - xcodes
      - youtube-dl
      - zlib
      - zsh
      - zoxide
      - teamookla/speedtest/speedtest
  notify: Homebrew Nginx Restart
