---
- name: homebrew tap
  tags: homebrew,homebrew-tap
  community.general.homebrew_tap:
    name:
      - homebrew/cask-fonts
      - homebrew/cask-versions
      - homebrew/services
      - teamookla/speedtest
    state: present
